export const EMAIL_ENCRYPTION_TYPES = {
  SSL: 'SSL',
  TLS: 'TLS',
  NONE: 'None',
};
export const DEFAULT_SMTP_PORT = 587;
export const DEFAULT_IMAP_PORT = 993;
export const DEFAULT_SMTP_ENCRYPTION = EMAIL_ENCRYPTION_TYPES.SSL;
export const DEFAULT_IMAP_ENCRYPTION = EMAIL_ENCRYPTION_TYPES.SSL;
export const DEFAULT_MESSAGE_PER_DAY = 200;
